In [1]:
import numpy as np

In [2]:
arr = np.linspace(0, 10, 10, dtype='int8')
print(arr)

[ 0  1  2  3  4  5  6  7  8 10]


In [4]:
indices_cond = arr > 5
print(indices_cond)

[False False False False False False  True  True  True  True]


In [5]:
arr[indices_cond]

array([ 6,  7,  8, 10], dtype=int8)

In [6]:
arr[(indices_cond) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [9]:
arr[arr > 5] = 99
print(arr)

[ 0  1  2  3  4  5 99 99 99 99]
