In [1]:
import numpy as np

In [3]:
arr = np.arange(1, 11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
trozo_arr = arr[0:6]
print(trozo_arr)

[1 2 3 4 5 6]


In [8]:
trozo_arr[:] = 0
print(trozo_arr)

[0 0 0 0 0 0]


In [10]:
arr_copy = arr.copy()
arr_copy[:] = 0
print(arr_copy)
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[ 0  0  0  0  0  0  7  8  9 10]
