In [2]:
import numpy as np

In [4]:
list(range(0, 10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.zeros((10, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones((10, 10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [14]:
np.linspace(0, 10, 10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [16]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [18]:
np.random.rand()

0.1769318444914032

In [20]:
np.random.randn(4)

array([ 0.83451597, -0.0190565 ,  0.50612641,  0.21949464])

In [22]:
np.random.rand(5, 5)

array([[0.29278364, 0.03534206, 0.59571304, 0.70056576, 0.51542187],
       [0.65309401, 0.80591421, 0.67683991, 0.44509023, 0.48298623],
       [0.22490923, 0.4401972 , 0.54804727, 0.44144366, 0.19216108],
       [0.50493322, 0.79782385, 0.1696294 , 0.04190766, 0.07384298],
       [0.42705359, 0.09928604, 0.3569565 , 0.6695385 , 0.14584897]])

In [25]:
np.random.randint(5)

0

In [27]:
np.random.randint(1, 100, (10, 10))

array([[91, 17, 78, 12, 77, 21, 95,  3, 16, 20],
       [74,  9, 73, 60, 95, 39, 82, 10, 44, 56],
       [68,  3, 22, 97, 53, 17, 99, 64,  9, 83],
       [27, 94, 48, 65, 96,  7, 20, 81, 60, 38],
       [ 3, 81, 77, 79, 28, 36, 10, 60,  2, 47],
       [92, 42, 60, 75, 55, 89, 46, 83, 12, 11],
       [87, 71,  3, 76, 97, 73,  6, 39, 94, 90],
       [29, 83,  4, 18, 60, 77, 43, 72, 52, 27],
       [73, 88, 11, 31, 22, 51, 96, 53, 17, 23],
       [ 1, 55, 53, 46, 69, 47, 46, 91,  4, 57]])