In [6]:
import numpy as np

In [16]:
arr = np.array([1, 2, 3])
print(arr)
arr.dtype

[1 2 3]


dtype('int64')

In [11]:
arr = np.array([1, 2, 3], dtype='float64')
print(arr)
arr.dtype

[1. 2. 3.]


dtype('float64')

In [18]:
arr

array([1, 2, 3])

In [24]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.bool_)
print(arr)

[False  True  True  True]


In [25]:
arr = np.array([0, 1, 2, 3])
arr = arr.astype(np.string_)
print(arr)

[b'0' b'1' b'2' b'3']
