In [2]:
import numpy as np

In [6]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [8]:
vector = np.array([1, 2, 3, 4])
print(vector)
vector.ndim

[1 2 3 4]


1

In [10]:
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
matrix.ndim

[[1 2 3]
 [4 5 6]]


2

In [13]:
tensor = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

## Add or remove dimensions

In [19]:
vector = np.array([1, 2, 3, 4], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3 4]]]]]]]]]]


10

In [18]:
expand = np.expand_dims(np.array([1, 2, 3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [21]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3 4]]]]]]]]]] 10
[1 2 3 4] 1
