In [2]:
import numpy as np

In [5]:
arr = np.random.randint(1, 20, 10)

In [8]:
matriz = arr.reshape(2, 5)
matriz

array([[14,  1,  3, 15,  2],
       [ 8,  2,  1, 17, 16]])

In [9]:
arr

array([14,  1,  3, 15,  2,  8,  2,  1, 17, 16])

In [11]:
arr.max()

17

In [13]:
matriz.max()

17

In [14]:
matriz.max(0)

array([14,  2,  3, 17, 16])

In [17]:
arr.argmax()

8

In [18]:
matriz.argmax(0)

array([0, 1, 0, 1, 1])

In [19]:
arr.min()

1

In [20]:
matriz.argmin(0)

array([1, 0, 1, 0, 0])

In [21]:
arr.ptp()

16

In [22]:
arr

array([14,  1,  3, 15,  2,  8,  2,  1, 17, 16])

In [23]:
matriz.ptp(0)

array([ 6,  1,  2,  2, 14])

In [25]:
np.percentile(arr, 50)

5.5

In [26]:
arr.sort()
arr

array([ 1,  1,  2,  2,  3,  8, 14, 15, 16, 17])

In [27]:
np.median(arr)

5.5

In [28]:
np.median(matriz, 0)

array([ 4.5,  7.5,  8.5,  9. , 10. ])

In [32]:
np.std(arr)

6.518435395092905

In [33]:
np.var(arr)

42.49

In [35]:
np.mean(arr)

7.9

In [58]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 6])

In [59]:
np.concatenate((a, b), axis=0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [62]:
a.ndim

2

In [63]:
b = np.expand_dims(b, axis=0)

In [65]:
np.concatenate((a, b), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
np.concatenate((a, b.T), axis=1) 

array([[1, 2, 5],
       [3, 4, 6]])