In [3]:
import numpy as np 
lista = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [7]:
arr = np.array(lista)

In [8]:
type(arr)

numpy.ndarray

In [10]:
matriz = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
arr[0]

1

In [14]:
arr[6] + arr[7]

15

In [18]:
matriz[0, 2]

3

In [19]:
arr[0:3]

array([1, 2, 3])

In [20]:
arr[::3]

array([ 1,  4,  7, 10])

In [22]:
# create matriz 3d
matriz3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
matriz3d

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])