In [3]:
import numpy as np

In [6]:
list = [1, 2,]
print(list)

[1, 2]


In [7]:
list * 2

[1, 2, 1, 2]

In [10]:
arr = np.arange(0, 10)
print(arr)
arr2 = arr.copy()

[0 1 2 3 4 5 6 7 8 9]


In [11]:
arr2 * 2 

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [12]:
arr2 ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [13]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
matriz = arr.reshape(2, 5)
print(matriz)
matriz2 = matriz.copy()

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [17]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [21]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

In [22]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [23]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])