In [5]:
import numpy as np

In [5]:
arr = np.random.randint(1, 10,(3, 2))

In [7]:
arr.shape

(3, 2)

In [9]:
arr

array([[2, 7],
       [6, 3],
       [5, 6]])

In [11]:
arr.reshape(1, 6)

array([[2, 7, 6, 3, 5, 6]])

In [16]:
arr.reshape(2, 3)

array([[2, 7, 6],
       [3, 5, 6]])

In [19]:
np.reshape(arr, (3, 2))

array([[2, 7],
       [6, 3],
       [5, 6]])

In [23]:
np.reshape(arr, (2, 3), 'C')

array([[2, 7, 6],
       [3, 5, 6]])

In [25]:
np.reshape(arr, (2, 3), 'F')

array([[2, 5, 3],
       [6, 7, 6]])

In [28]:
np.reshape(arr, (2, 3), 'A')

array([[2, 7, 6],
       [3, 5, 6]])

In [7]:
tensor = np.random.randint(1, 10,(3, 2, 2))
print(tensor)

[[[4 4]
  [7 1]]

 [[4 6]
  [9 1]]

 [[5 9]
  [2 3]]]


In [10]:
np.reshape(tensor, (4, 3))

array([[4, 4, 7],
       [1, 4, 6],
       [9, 1, 5],
       [9, 2, 3]])